[package]
name = "miden-prover"
version = "0.26.0"
description = "Miden VM prover"
documentation = "https://docs.rs/miden-prover"
readme = "README.md"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "prover", "stark", "zkp"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[features]
arbitrary = ["dep:proptest"]
default = ["std"]
concurrent = ["std", "miden-air/concurrent", "miden-crypto/concurrent", "miden-processor/concurrent"]
std = ["miden-air/std", "miden-debug-types/std", "miden-processor/std"]
testing = ["arbitrary"]

[dependencies]
# Miden dependencies
miden-air.workspace = true
miden-core.workspace = true
miden-processor.workspace = true
miden-crypto.workspace = true

# External dependencies
proptest = { workspace = true, optional = true }
serde.workspace = true
serde-wincode.workspace = true
tracing.workspace = true
wincode.workspace = true

[dev-dependencies]
miden-assembly.workspace = true
miden-debug-types.workspace = true
miden-test-serde-macros.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
