# Runs test related jobs.

name: test

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  test:
    name: test ${{matrix.toolchain}} on ubuntu with ${{matrix.args}}
    runs-on: warp-ubuntu-latest-x64-4x
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]
        args: [default, no-std, large-smt]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6.0.3
        with:
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - uses: taiki-e/install-action@0631aa6515c7d545823c67cfae7ef4fc7f490154 # pin@v2.81.8
        with:
          tool: cargo-nextest
      - uses: WarpBuilds/rust-cache@9d0cc3090d9c87de74ea67617b246e978735b1a1 # pin@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Install LLVM/Clang
        if: ${{ matrix.args == 'large-smt' }}
        uses: ./.github/actions/install-llvm
        with:
          version: "17"
      - name: Perform tests
        run: |
          rustup update --no-self-update ${{matrix.toolchain}}
          rustup default ${{ matrix.toolchain }}
          make test-${{matrix.args}}

  test-smt-concurrent:
    name: test-smt-concurrent ${{ matrix.toolchain }}
    runs-on: warp-ubuntu-latest-x64-4x
    if: ${{ github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'next') }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6.0.3
        with:
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - uses: taiki-e/install-action@0631aa6515c7d545823c67cfae7ef4fc7f490154 # pin@v2.81.8
        with:
          tool: cargo-nextest
      - uses: WarpBuilds/rust-cache@9d0cc3090d9c87de74ea67617b246e978735b1a1 # pin@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Perform concurrent SMT tests
        run: |
          rustup update --no-self-update ${{matrix.toolchain}}
          rustup default ${{ matrix.toolchain }}
          make test-smt-concurrent

  doc-tests:
    name: doc-tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'next') }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6.0.3
        with:
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # pin@v2.9.1
      - name: Install LLVM/Clang
        uses: ./.github/actions/install-llvm
        with:
          version: "17"
      - name: Run doc-tests
        run: |
          rustup update --no-self-update
          rustup default ${{ matrix.toolchain }}
          make test-docs

  test-p3-parallel:
    name: test Miden STARK crates parallel ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6.0.3
        with:
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - name: Run Miden STARK crate parallel tests
        run: |
          rustup update --no-self-update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          make test-p3-parallel
