name: Publish workspace to crates.io

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: ${{ github.repository_owner == '0xMiden' }}
    uses: 0xMiden/.github/.github/workflows/workspace-release.yml@d34ae3cd29234c5aa4d3ab57635b30563471c3c3
    with:
      mode: publish
      msrv_script_path: scripts/check-msrv.sh
      verify_target_ref_head: true
      environment_name: release
